name: meetmax
description: "Social Media App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  get: ^4.6.6
  http: ^1.2.2
  mime: ^2.0.0
  intl: ^0.19.0
  image: ^4.3.0
  lottie: ^3.1.3
  badges: ^3.1.2
  timeago: ^3.7.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  video_player: ^2.9.2
  path_provider: ^2.1.5
  toastification: ^2.3.0
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0
  widget_and_text_animator: ^1.1.5
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf